image_key_order:
  - isaac_ros.noble.ros2_jazzy.realsense.nova_carter
context_overrides:
  isaac_ros: ..
  noble: ..
cache_to_registry_names: []
cache_from_registry_names:
  - nvcr.io/nvidia/isaac/ros
remote_builder: []